---
- name: Configure LEAPP assets for AAP
  hosts: controller
  connection: local
  tasks:
    - name: Create Credentials
      ansible.builtin.include_role:
        name: infra.controller_configuration.credentials
      vars:
        controller_configuration_credentials_secure_logging: "{{ nolog_debug }}"

    - name: Create Projects
      ansible.builtin.include_role:
        name: infra.controller_configuration.projects

    - name: Create Inventories
      ansible.builtin.include_role:
        name: infra.controller_configuration.inventories

    - name: Create Inventory Sources
      ansible.builtin.include_role:
        name: infra.controller_configuration.inventory_sources

    - name: Create Job Templates
      ansible.builtin.include_role:
        name: infra.controller_configuration.job_templates
