---
- name: Configure LEAPP assets for AAP
  hosts: all
  connection: local
  vars_files:
    - "../vars/controller/auth.yml"
    - "../vars/controller/credentials.yml"
    - "../vars/controller/inventories.yml"
    - "../vars/controller/inventory_sources.yml"
    - "../vars/controller/vault.yml"
  tasks:
    - name: Create custom credential type
      ansible.builtin.include_role:
        name: infra.controller_configuration.credential_types

    - name: Create credentials
      ansible.builtin.include_role:
        name: infra.controller_configuration.credentials

    - name: Create Inventories
      ansible.builtin.include_role:
        name: infra.controller_configuration.inventories

    - name: Create Inventory Sources
      ansible.builtin.include_role:
        name: infra.controller_configuration.inventory_sources
