---
- name: Configure LEAPP assets for AAP
  hosts: all
  connection: local
  tasks:
    - name: Create Inventories
      ansible.builtin.include_role:
        name: infra.controller_configuration.inventories

    - name: Create Inventory Sources
      ansible.builtin.include_role:
        name: infra.controller_configuration.inventory_sources
